### ISSUE TITLE
TypeError [ERR_UNESCAPED_CHARACTERS]: Request path contains unescaped characters

### ISSUE THREAD

**Issue by GreenDiscord** [lacymorrow/album-art#12]
Some albums leave this error message

**Comment by n1ce-0ne** [comment]
str_replace('(','\(',str_replace(')','\)',str_replace("'","\'",str_replace('&','\&',$title))))

**Comment by GreenDiscord** [comment]
Yeah, used encodeURI or smthing like that

**Comment by lacymorrow** [comment]
I think it's worth validating in the library, do you have an example album which causes this error?

**Comment by GreenDiscord** [comment]
> I think it's worth validating in the library, do you have an example album which causes this error?

Yeah, ended up being because of special characters and stuff

**Comment by n1ce-0ne** [comment]
ive found so far its anything with
 ( ) ' & 
all need a backslash
