### ISSUE TITLE
Returning Error instead of throwing?

### ISSUE THREAD

**Issue by foxxyz** [lacymorrow/album-art#13]
I got tripped up on this and was wondering if this was a conscious choice or something that I could submit a PR for:

Calling this and trying to catch an invalid response doesn't work:
```
try {
    const res = await albumArt("some string which has no results")
} catch (e) {
    // This will never fire
    console.log('No Results')
}
```

After reading through your code, I realized the error is returned instead of thrown.

```
const res = await albumArt("some string which has no results")
if (e instanceof Error) console.log('No Results')
```

Seems unconventional, any reason for that?

**Comment by n1ce-0ne** [comment]
all i do with php is make the call & check for '/image/' with if(strpos($link,'/image/') !== false)
if i were using js i'd probably do the same

**Comment by lacymorrow** [comment]
So... it was probably an error, and I'd probably accept a PR, the issue is that this library has been untouched for so long I'm worried about breaking pre-existing implementations. 

I would want to release a new major version at the least. Go ahead and PR if you like and I'll test and potentially release it when I have a day free.

**Comment by GreenDiscord** [comment]
> So... it was probably an error, and I'd probably accept a PR, the issue is that this library has been untouched for so long I'm worried about breaking pre-existing implementations. 
> 
> 
> 
> I would want to release a new major version at the least. Go ahead and PR if you like and I'll test and potentially release it when I have a day free.

Most work around a just turn the object into a  string
