### ISSUE TITLE
Seem's like it's still using Last.fm's api?

### ISSUE THREAD

**Issue by GreenDiscord** [lacymorrow/album-art#15]
And this is causing many no album art work finds on massive songs

**Comment by lacymorrow** [comment]
I'll take a look this week.

**Comment by GreenDiscord** [comment]
> I'll take a look this week.

Just took a look and it seems npm installed 1.0.4, strange....

**Comment by lacymorrow** [comment]
Yep, definitely using spotify, checkout the index.js
