### ISSUE TITLE
Change in last.fm database?

### ISSUE THREAD

**Issue by liberatorcnx** [lacymorrow/album-art#3]
I am getting lowest resolution artwork when requesting artist art without a specified resolution.  The code below from index.js :
```
} else if (json[method] && json[method].image) {
	    	// Return largest image
	    	var i = json[method].image.length - 1;
```
 This actually returns a small image (from size":"").  Changing to length - 2  solves the problem and grabs the 'mega' image:
```
} else if (json[method] && json[method].image) {
	    	// Return largest image
	    	var i = json[method].image.length - 2;
```
I was also getting many failures with artists thaat included '&' (ampersand) in their name.  Adding a single line after line 17 thus solved the problem;
```
	var http = require('http');
	var artist = artist.replace ("&", "and");
	var options = {
	  host: 'ws.audioscrobbler.com',
	  port: 80,
	  path: encodeURI('/2.0/?format=json&api_key=' + apiKey + '&method=' + method + '.getinfo&artist=' + artist + '&album=' + album)
	};
```

**Comment by lacymorrow** [comment]
Excellent, I'm glad you were able to figure this out, they may have changed their API. If you go ahead and submit a pull request I will merge it into the master rrepo
