### ISSUE TITLE
Only using artist and size in request.

### ISSUE THREAD

**Issue by liberatorcnx** [lacymorrow/album-art#6]
I have been trying to submit requests sending only (artist, size, cb).  album-art assumes that the second string is 'album'....  I have solved my immediate problem with the following change to the start of index.js:
```
'use strict';
module.exports = function (artist, album, size, cb) {
	var sizes = ['small', 'medium', 'large', 'extralarge', 'mega'];
	if (typeof artist !== 'string') {
		throw new Error('Expected a string');
	}
	if (typeof album === 'function') {  //This is just artist - no album or size
		cb = album;
		album = size = null;
	} else if (typeof size === 'function') {  //3rd element is cb so we now have to check if the 2nd element (album) IS album or size!
		cb = size;
		if (sizes.indexOf(album) > -1)  //2nd element matches a valid size (problem if album name is a valid size?)
		size = album;
		album = null;
	}
	var data = '';
```
The only problem with this is if someone were to send a request 'artist, album, cb' (no size) and the album name matched a valid size name then it would erroneously provide the artist artwork.

Any thoughts?

**Comment by liberatorcnx** [comment]
My bad!  I just realized that I can just send null for album name and all works OK.....

**Comment by lacymorrow** [comment]
Sorry for the delayed comment, this is great! thank you for the update

**Comment by liberatorcnx** [comment]
Lacy - can you forsee any problem with sending 'null' as album name?  I want to be sure before I submit a PR for Volumio2.  Thanks!

**Comment by lacymorrow** [comment]
Nope, I would do it the same way ++

**Comment by liberatorcnx** [comment]
Ok - many thanks. I will close this issue now!
