### ISSUE TITLE
npm version

### ISSUE THREAD

**Issue by liberatorcnx** [lacymorrow/album-art#7]
An app that I am involved in developing ([Volumio](https://github.com/volumio/Volumio2)) seems to have a problem with updating the album-art node module.

When I queried this I was told 

> I looked at the npm module albumart, and altough in the source repo lists 1.0.4 as latest version, npm still lists 1.0.2... Could you notify the module publisher to bump the version in npm as well?

I'm not sure what is required but is that something you could do?

Many thanks!

**Comment by lacymorrow** [comment]
Thanks for the heads up @liberatorcnx! Everything should be up to date 👍
