### ISSUE TITLE
Lastfm API doesn't return correct images anymore

### ISSUE THREAD

**Issue by lffloyd** [lacymorrow/album-art#9]
Hello there.

They made an announcement [here](https://getsatisfaction.com/lastfm/topics/api-announcement-dac8oefw5vrxq).

I'm creating this issue basically to clarify this behavior for anyone that had into the same problem. However, as you can see, this cannot be solved.

**Comment by lacymorrow** [comment]
Thanks for raising this @lffloyd, I'll work on updating this library, potentially using a different service for the images.

**Comment by lffloyd** [comment]
Thanks for the reply, @lacymorrow, and also thanks for your work!

See ya!

**Comment by lacymorrow** [comment]
Thanks @lffloyd :)

I've updated this library to get things back to normal. I'm ditching Last.fm and have switched over to using Spotify's API. We'll see how this works, please feel free to report any issues.
Cheers!
